var annotated_dup =
[
    [ "fmt", null, [
      [ "formatter< UN::CommandListState >", "structfmt_1_1formatter_3_01UN_1_1CommandListState_01_4.html", null ],
      [ "formatter< UN::MemorySizeImpl< T > >", "structfmt_1_1formatter_3_01UN_1_1MemorySizeImpl_3_01T_01_4_01_4.html", null ],
      [ "formatter< UN::ResultCode >", "structfmt_1_1formatter_3_01UN_1_1ResultCode_01_4.html", null ],
      [ "formatter< VkResult >", "structfmt_1_1formatter_3_01VkResult_01_4.html", null ]
    ] ],
    [ "UN", null, [
      [ "Internal", null, [
        [ "PtrRef", "classUN_1_1Internal_1_1PtrRef.html", null ],
        [ "SVWrapper", "structUN_1_1Internal_1_1SVWrapper.html", "structUN_1_1Internal_1_1SVWrapper" ]
      ] ],
      [ "AdapterInfo", "structUN_1_1AdapterInfo.html", "structUN_1_1AdapterInfo" ],
      [ "ArraySlice", "classUN_1_1ArraySlice.html", "classUN_1_1ArraySlice" ],
      [ "BufferBase", "classUN_1_1BufferBase.html", "classUN_1_1BufferBase" ],
      [ "BufferCopyRegion", "structUN_1_1BufferCopyRegion.html", "structUN_1_1BufferCopyRegion" ],
      [ "BufferDesc", "structUN_1_1BufferDesc.html", "structUN_1_1BufferDesc" ],
      [ "CommandListBase", "classUN_1_1CommandListBase.html", "classUN_1_1CommandListBase" ],
      [ "CommandListBuilder", "classUN_1_1CommandListBuilder.html", "classUN_1_1CommandListBuilder" ],
      [ "CommandListDesc", "structUN_1_1CommandListDesc.html", "structUN_1_1CommandListDesc" ],
      [ "CompilerDefinition", "structUN_1_1CompilerDefinition.html", "structUN_1_1CompilerDefinition" ],
      [ "ComputeDeviceDesc", "structUN_1_1ComputeDeviceDesc.html", "structUN_1_1ComputeDeviceDesc" ],
      [ "DeviceFactoryDesc", "structUN_1_1DeviceFactoryDesc.html", "structUN_1_1DeviceFactoryDesc" ],
      [ "DeviceMemoryBase", "classUN_1_1DeviceMemoryBase.html", "classUN_1_1DeviceMemoryBase" ],
      [ "DeviceMemoryDesc", "structUN_1_1DeviceMemoryDesc.html", "structUN_1_1DeviceMemoryDesc" ],
      [ "DeviceMemorySlice", "classUN_1_1DeviceMemorySlice.html", "classUN_1_1DeviceMemorySlice" ],
      [ "DeviceObjectBase", "classUN_1_1DeviceObjectBase.html", "classUN_1_1DeviceObjectBase" ],
      [ "DynamicLibrary", "classUN_1_1DynamicLibrary.html", "classUN_1_1DynamicLibrary" ],
      [ "FenceBase", "classUN_1_1FenceBase.html", null ],
      [ "FenceDesc", "structUN_1_1FenceDesc.html", "structUN_1_1FenceDesc" ],
      [ "HeapArray", "classUN_1_1HeapArray.html", "classUN_1_1HeapArray" ],
      [ "IAllocator", "classUN_1_1IAllocator.html", "classUN_1_1IAllocator" ],
      [ "IBuffer", "classUN_1_1IBuffer.html", "classUN_1_1IBuffer" ],
      [ "ICommandList", "classUN_1_1ICommandList.html", "classUN_1_1ICommandList" ],
      [ "IComputeDevice", "classUN_1_1IComputeDevice.html", "classUN_1_1IComputeDevice" ],
      [ "IDeviceFactory", "classUN_1_1IDeviceFactory.html", "classUN_1_1IDeviceFactory" ],
      [ "IDeviceMemory", "classUN_1_1IDeviceMemory.html", "classUN_1_1IDeviceMemory" ],
      [ "IDeviceObject", "classUN_1_1IDeviceObject.html", "classUN_1_1IDeviceObject" ],
      [ "IFence", "classUN_1_1IFence.html", "classUN_1_1IFence" ],
      [ "IKernel", "classUN_1_1IKernel.html", "classUN_1_1IKernel" ],
      [ "IKernelCompiler", "classUN_1_1IKernelCompiler.html", "classUN_1_1IKernelCompiler" ],
      [ "IncludeHandler", "classUN_1_1IncludeHandler.html", null ],
      [ "IObject", "classUN_1_1IObject.html", "classUN_1_1IObject" ],
      [ "IResourceBinding", "classUN_1_1IResourceBinding.html", "classUN_1_1IResourceBinding" ],
      [ "IVulkanDescriptorAllocator", "classUN_1_1IVulkanDescriptorAllocator.html", null ],
      [ "KernelBase", "classUN_1_1KernelBase.html", "classUN_1_1KernelBase" ],
      [ "KernelCompiler", "classUN_1_1KernelCompiler.html", null ],
      [ "KernelCompilerArgs", "structUN_1_1KernelCompilerArgs.html", "structUN_1_1KernelCompilerArgs" ],
      [ "KernelCompilerDesc", "structUN_1_1KernelCompilerDesc.html", "structUN_1_1KernelCompilerDesc" ],
      [ "KernelDesc", "structUN_1_1KernelDesc.html", "structUN_1_1KernelDesc" ],
      [ "KernelResourceDesc", "structUN_1_1KernelResourceDesc.html", "structUN_1_1KernelResourceDesc" ],
      [ "MemoryBarrierDesc", "structUN_1_1MemoryBarrierDesc.html", "structUN_1_1MemoryBarrierDesc" ],
      [ "MemoryMapHelper", "classUN_1_1MemoryMapHelper.html", "classUN_1_1MemoryMapHelper" ],
      [ "MemorySizeImpl", "classUN_1_1MemorySizeImpl.html", "classUN_1_1MemorySizeImpl" ],
      [ "Object", "classUN_1_1Object.html", "classUN_1_1Object" ],
      [ "Ptr", "classUN_1_1Ptr.html", "classUN_1_1Ptr" ],
      [ "ReferenceCounter", "classUN_1_1ReferenceCounter.html", "classUN_1_1ReferenceCounter" ],
      [ "ResourceBindingBase", "classUN_1_1ResourceBindingBase.html", null ],
      [ "ResourceBindingDesc", "structUN_1_1ResourceBindingDesc.html", "structUN_1_1ResourceBindingDesc" ],
      [ "SystemAllocator", "classUN_1_1SystemAllocator.html", "classUN_1_1SystemAllocator" ],
      [ "VulkanBuffer", "classUN_1_1VulkanBuffer.html", "classUN_1_1VulkanBuffer" ],
      [ "VulkanCommandList", "classUN_1_1VulkanCommandList.html", "classUN_1_1VulkanCommandList" ],
      [ "VulkanComputeDevice", "classUN_1_1VulkanComputeDevice.html", "classUN_1_1VulkanComputeDevice" ],
      [ "VulkanDescriptorAllocator", "classUN_1_1VulkanDescriptorAllocator.html", "classUN_1_1VulkanDescriptorAllocator" ],
      [ "VulkanDescriptorAllocatorDesc", "structUN_1_1VulkanDescriptorAllocatorDesc.html", null ],
      [ "VulkanDeviceFactory", "classUN_1_1VulkanDeviceFactory.html", "classUN_1_1VulkanDeviceFactory" ],
      [ "VulkanDeviceMemory", "classUN_1_1VulkanDeviceMemory.html", "classUN_1_1VulkanDeviceMemory" ],
      [ "VulkanFence", "classUN_1_1VulkanFence.html", "classUN_1_1VulkanFence" ],
      [ "VulkanKernel", "classUN_1_1VulkanKernel.html", "classUN_1_1VulkanKernel" ],
      [ "VulkanQueueFamily", "structUN_1_1VulkanQueueFamily.html", null ],
      [ "VulkanResourceBinding", "classUN_1_1VulkanResourceBinding.html", "classUN_1_1VulkanResourceBinding" ]
    ] ],
    [ "DerivedTestObject", "classDerivedTestObject.html", null ],
    [ "TestObject", "classTestObject.html", null ]
];